# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
cloned_from = "In0I4ijYMupozbXe9uyUO7"
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 3
name = "Default starter for JavaScript"
service_id = "In0I4ijYMupozbXe9uyUO7"
